### ISSUE TITLE
UI API

### ISSUE THREAD

**Issue by zacharyburkett** [split-cube-studios/ardent#33]
We likely need to develop our own UI framework, as any framework we use will need to support all Ardent backends.

It could be possible to use backend-specific frameworks, but I'd prefer to keep as much behavior consistent between backends as possible.

Maybe some sort of framework built on-top of the image and input interfaces?

The scope is somewhat hazy for a MVP feature. We will at least need things like relative layout APIs, buttons, containers, etc.

**Comment by jakubDoka** [comment]
Maybe i can attempt this one. Does backend allow drawing vertices directly? To support flexible pannels some triangle geometry is needed.
