### ISSUE TITLE
Engine | Move engine/keys.go into new engine/keys package

### ISSUE THREAD

**Issue by madxmike** [split-cube-studios/ardent#34]
Currently to get a certain key you need to do something akin to engine.KeyB. A possibly better way to structure this would to have a engine/keys package that would hold all of the keys allowing access with keys.B instead. Benefits would be a clearer access and de cluttering the engine namespace. 

One consideration is non-key inputs. Should these be in their own package like engine/gamepad, engine/mouse, etc or maybe something like engine/input? Would need some input on it.

**Comment by zacharyburkett** [comment]
I think exposing each input type via its own package would make sense. Semantically in code it would be very readable.

**Comment by madxmike** [comment]
Would we just want to group all of this under something like engine/input

engine/input/keys
engine/input/gamepad
...

possibly move input related things like the interface into here (input.Input kinda feels bad)?

**Comment by zacharyburkett** [comment]
I think I would prefer to not have an encompassing `input` package. Depends on implementation I suppose.

**Comment by madxmike** [comment]
One other idea would be to split the Input interface into seperate interfaces in each package. So engine/keys would have some type of KeyInput interface with all the IsKeyPressed methods defined same with the mouse events. Then in the Input interface we could just compose these together into a larger interface.

**Comment by zacharyburkett** [comment]
I don't think input needs to be abstracted to an interface, since all input methods will have some unique features. I think using explicit "implementations" (still each backed by a backend implementation) is the way to go.

**Comment by madxmike** [comment]
Closed for #39
