### ISSUE TITLE
Vec2.AngleTo is not a correct way to calculate angle between two vectors

### ISSUE THREAD

**Issue by jakubDoka** [split-cube-studios/ardent#44]
Going trought the project as a big math fan a hed to look inside vec2.go and i found this interesting function:
https://github.com/split-cube-studios/ardent/blob/826c7a4f5eabc5ce44fe2d80846ed0133bf9b23a/engine/vec2.go#L10
First it hit me as some super smart solution but when i drawn it on paper it did not make sence. I also compared it to my solution witch is slower but tested and as i expected, your AngleTo yields incorrect values. 

Now to fix this i present my solution:
```go
// AngleTo returns angle between u and v.
func (u Vec) AngleTo(v Vec) float64 {
	a := math.Abs(u.Angle() - v.Angle())
	if a > math.Pi {
		return 2*math.Pi - a
	}
	return a
}
```
Using dot product for this appeard to be slower and could produce NaN if angle was too small, that why logic is used instead.

**Comment by zacharyburkett** [comment]
This method actually works exactly as intended. A fix would be to update the docstring to something like `AngleTo returns the angle from the endpoint of u to the endpoint of v.`
